# Generated by Django 4.0.6 on 2022-07-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['-created_at'], 'verbose_name': 'карточку', 'verbose_name_plural': 'Библиотека'},
        ),
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
