# Generated by Django 4.0.6 on 2022-08-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bots',
            name='token',
        ),
        migrations.AddField(
            model_name='bots',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
