# Generated by Django 4.0.6 on 2022-08-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bots_tg_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='tg_name',
            field=models.CharField(max_length=150, verbose_name='Название в Телеграмм'),
        ),
    ]
